import type { Request, Response, NextFunction, Application } from 'express';
import { Options } from './options';
import { Tag } from './helpers';
import { Paths } from './paths';

/**
 * Internal build stub (replace with your real resolver/bundler)
 */
async function buildBundle(options: Options): Promise<{ code: string }> {
	// TODO: implement real resolution based on:
	// - npm: scope/pkg@version
	// - git: host/owner/repo@commit
	// - digest: sha256-... | sha256u-...
	// - options.module, target, format, environment, min, etc.
	const code = `// Generated by BeyondJS\n` + `export function hello(){console.log("hi")}\n`;
	return { code };
}

/**
 * Routes for module serving
 */
export class ModulesRoutes {
	static setup(app: Application) {
		// NPM Registry (scoped packages)
		app.get('/m/@:scope/:pkg@:ver/modules/:mod', this.module);

		// NPM Registry (unscoped packages)
		app.get('/m/:pkg@:ver/modules/:mod', this.module);

		// Other registries (scoped)
		app.get('/m/:rid/@:scope/:pkg@:ver/modules/:mod', this.module);

		// Other registries (unscoped)
		app.get('/m/:rid/:pkg@:ver/modules/:mod', this.module);

		// git by commit
		app.get('/m/git/:host/:owner/:repo@:commit/modules/:mod', this.module);

		// by immutable digest
		app.get('/m/digest/:digest/modules/:mod', this.module);
	}

	static async module(request: Request, response: Response, next: NextFunction) {
		try {
			// Build options from request
			const options = new Options(request);

			// Build or fetch bundle bytes
			const { code } = await buildBundle(options);
			const body = typeof code === 'string' ? Buffer.from(code, 'utf-8') : Buffer.from(code);

			// ETag (strong) based on full bytes, as per responses.yaml
			const etag = Tag.etag(code);
			if (Tag.notmod(request, response, etag)) return;

			// Source maps
			if (options.sourcemap === 'external') {
				const map = Paths.map(options);
				response.setHeader('SourceMap', map);
				response.setHeader('X-SourceMap', map);
			}

			// .d.ts link
			if (options.types) {
				const path = Paths.dts(options);
				response.append('Link', `<${path}>; rel="describedby"; type="text/plain"`);
			}

			// CSS link
			if (options.css) {
				const path = Paths.css(options);
				response.append('Link', `<${path}>; rel="preload"; as="style"`);
			}

			// Headers
			response.type('application/javascript; charset=utf-8');
			response.setHeader('ETag', etag);
			response.setHeader(
				'Cache-Control',
				options.environment === 'production' ? 'public, max-age=31536000, immutable' : 'no-store'
			);

			// Body
			response.status(200).send(body);
		} catch (error) {
			next(error);
		}
	}
}
